const curledColors = [
{"hexCode":"f6f6f6","name":"Pending"},
{"hexCode":"e2e2e2","name":"Angel Feathers"},
{"hexCode":"8b8b8b","name":"Dark Moon"},
{"hexCode":"6f6f6f","name":"Chimney Sweep"},
{"hexCode":"3e3e3e","name":"Batakapa"},
{"hexCode":"222222","name":"Catch 22"},
{"hexCode":"fff7f9","name":"Light Strawberry Whipped Cream"},
{"hexCode":"ffdce5","name":"Butterfly Mellow"},
{"hexCode":"ff3b8d","name":"Blow Out Bubblegum"},
{"hexCode":"db0072","name":null},
{"hexCode":"800040","name":"Misali Wine"},
{"hexCode":"4c0023","name":"Brilliant Blackberry"},
{"hexCode":"fff8f8","name":"Just A Spoonful Of Sugar"},
{"hexCode":"ffdddf","name":"Pink Basalt"},
{"hexCode":"ff426c","name":null},
{"hexCode":"de0051","name":"Submissive Rouge"},
{"hexCode":"82002c","name":null},
{"hexCode":"510018","name":"Willy Wonka Coat Purple"},
{"hexCode":"fff8f6","name":"Pale Baby Peaches"},
{"hexCode":"ffddd8","name":"Piggy Perfectionist"},
{"hexCode":"ff4647","name":null},
{"hexCode":"e0002b","name":null},
{"hexCode":"830014","name":"Royal Red"},
{"hexCode":"530003","name":null},
{"hexCode":"fff8f5","name":"White Mocha"},
{"hexCode":"ffded1","name":"Kitten Pink"},
{"hexCode":"fd4d00","name":"Cure Sunny Orange"},
{"hexCode":"cd3c00","name":null},
{"hexCode":"752100","name":"Muddy Red"},
{"hexCode":"401600","name":"40 Squared"},
{"hexCode":"fff8f3","name":"Blinded By The White"},
{"hexCode":"ffdfc6","name":null},
{"hexCode":"d57300","name":null},
{"hexCode":"ac5c00","name":"Crusty Sean"},
{"hexCode":"633300","name":null},
{"hexCode":"371d00","name":"Nigorange"},
{"hexCode":"fff8ef","name":"Scottish White"},
{"hexCode":"ffe0b2","name":"Pale Rosy Peach Pink Duhh"},
{"hexCode":"b98300","name":null},
{"hexCode":"926700","name":null},
{"hexCode":"523800","name":"Stained Oak"},
{"hexCode":"302100","name":"Bitter Brew"},
{"hexCode":"fff9e5","name":"Whipped Cream White II"},
{"hexCode":"ffe53e","name":null},
{"hexCode":"9c8b00","name":null},
{"hexCode":"7d6f00","name":"Rusty Golden Ring"},
{"hexCode":"463d00","name":"Rusty Old Garden"},
{"hexCode":"292300","name":"Grass On The Bottom Of The Boot"},
{"hexCode":"f7ffac","name":"Addison Rae"},
{"hexCode":"d5f200","name":null},
{"hexCode":"819300","name":"Greenish Yellow Green"},
{"hexCode":"677600","name":"Joey Cogs"},
{"hexCode":"394100","name":null},
{"hexCode":"222600","name":"Grayish Brownish Green But Not"},
{"hexCode":"e5ffc3","name":null},
{"hexCode":"98fb00","name":null},
{"hexCode":"5c9b00","name":null},
{"hexCode":"497c00","name":null},
{"hexCode":"264500","name":"Murky Swamp At Midnight"},
{"hexCode":"182600","name":"Trees At 7 Pm"},
{"hexCode":"e0ffd9","name":"Peaceful G"},
{"hexCode":"72ff6c","name":null},
{"hexCode":"00a21f","name":null},
{"hexCode":"008217","name":null},
{"hexCode":"004908","name":"Unplugged Leaf Green"},
{"hexCode":"062800","name":"Tangadion Green"},
{"hexCode":"dcffe6","name":"Paper Packets"},
{"hexCode":"5dffa2","name":null},
{"hexCode":"00a05a","name":null},
{"hexCode":"008147","name":"Forest Monkey"},
{"hexCode":"004825","name":null},
{"hexCode":"002812","name":null},
{"hexCode":"daffef","name":"Temisen Lightblue"},
{"hexCode":"42ffc6","name":"Blue Tooth"},
{"hexCode":"009f78","name":null},
{"hexCode":"007f5f","name":"Sub Human Scum"},
{"hexCode":"004734","name":null},
{"hexCode":"00281b","name":null},
{"hexCode":"d7fff7","name":null},
{"hexCode":"00ffe4","name":"Blinding Cyan"},
{"hexCode":"009e8c","name":"Hummingbird Iridescence"},
{"hexCode":"007c6e","name":null},
{"hexCode":"00443c","name":"Dark Mermaid"},
{"hexCode":"002722","name":null},
{"hexCode":"c4fffe","name":"Sad Boi Hours"},
{"hexCode":"00fafb","name":null},
{"hexCode":"00999a","name":null},
{"hexCode":"007a7b","name":null},
{"hexCode":"004344","name":"Viridian Rhudantre"},
{"hexCode":"002525","name":"Monster Under The Bed"},
{"hexCode":"dafaff","name":"16 O'clock"},
{"hexCode":"8df0ff","name":null},
{"hexCode":"0098a9","name":null},
{"hexCode":"007987","name":null},
{"hexCode":"004048","name":null},
{"hexCode":"002227","name":null},
{"hexCode":"e3f7ff","name":"Sea Mineral"},
{"hexCode":"aee9ff","name":"Baby Girl Blue"},
{"hexCode":"0094b4","name":"Bashful Blue Jay"},
{"hexCode":"007590","name":null},
{"hexCode":"00404f","name":"Sea Smart"},
{"hexCode":"001f28","name":null},
{"hexCode":"e8f6ff","name":"Minty Beluga"},
{"hexCode":"b9e3ff","name":"Mom"},
{"hexCode":"0092c5","name":"Weezer"},
{"hexCode":"00749d","name":null},
{"hexCode":"003c54","name":"Dark Washed Jacket"},
{"hexCode":"001d2a","name":null},
{"hexCode":"e8f2ff","name":"Home For The Weekend"},
{"hexCode":"c6e0ff","name":"Baby's Breath Blues"},
{"hexCode":"008fdb","name":null},
{"hexCode":"0071af","name":null},
{"hexCode":"003b5e","name":null},
{"hexCode":"001c30","name":null},
{"hexCode":"f0f4ff","name":"4 Feet Of Snow"},
{"hexCode":"d4e0ff","name":"Literally A Cloud"},
{"hexCode":"0089fc","name":null},
{"hexCode":"006dca","name":null},
{"hexCode":"00386d","name":null},
{"hexCode":"001a39","name":null},
{"hexCode":"f3f3ff","name":"Static White"},
{"hexCode":"deddff","name":"Vampiric Pale"},
{"hexCode":"657eff","name":null},
{"hexCode":"0061fc","name":"Aquis Blue"},
{"hexCode":"00328a","name":"Darkish Blueish Color"},
{"hexCode":"001649","name":null},
{"hexCode":"f7f1ff","name":"Ceibel"},
{"hexCode":"e8daff","name":"Stuck In Candy Floss"},
{"hexCode":"9b70ff","name":"3 AM In Tehran"},
{"hexCode":"794aff","name":null},
{"hexCode":"2d0fbf","name":null},
{"hexCode":"0b0074","name":null},
{"hexCode":"fdf4ff","name":"Perfect Pearly Pink"},
{"hexCode":"f7d9ff","name":"Lavender Llama"},
{"hexCode":"d150ff","name":null},
{"hexCode":"b01fe3","name":null},
{"hexCode":"660087","name":null},
{"hexCode":"3a004f","name":"Plum Pudding Party"},
{"hexCode":"fff3fc","name":"Pale Pink Cotton Candy"},
{"hexCode":"ffd7f6","name":"Baby Pink"},
{"hexCode":"f911e0","name":"Grossly Pink"},
{"hexCode":"ca00b6","name":"Lilicain"},
{"hexCode":"740068","name":"918kiss"},
{"hexCode":"44003c","name":"Dark Field"},
{"hexCode":"fff7fb","name":"Josie Pink"},
{"hexCode":"ffdcec","name":"Babygirl's"},
{"hexCode":"ff2fb2","name":"Victoria's Pink Secret"},
{"hexCode":"d2008f","name":null},
{"hexCode":"790051","name":null},
{"hexCode":"4b0030","name":null}]

const namedColors = curledColors.filter(cc => cc.name)